restore missing spring dependency for cucumber
causes: class java.lang.NoClassDefFoundError: org/springframework/expression/spel/standard/SpelExpressionParser